version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Hcmonitor12!
      - MSSQL_PID=Express
      - ACCEPT_EULA=Y
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    